version: "3"
services:
    fpm_app:
        build: fpm_app
        container_name: tmp_fpm_app
        ports:
            - 9000:9000
        volumes:
            - ./app:/var/www/
    nginx_app:
        build: nginx_app
        container_name: tmp_nginx_app
        ports:
            - 127.0.0.1:80:80
        volumes:
            - ./app:/var/www/
        depends_on:
            - fpm_app
        links:
            - fpm_app